# Generated by Django 5.1.2 on 2024-10-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apples', '0003_alter_product_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.URLField(),
        ),
    ]
