# Generated by Django 5.1.2 on 2024-10-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apples', '0004_alter_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('herbal', 'Herbal Supplements'), ('essential', 'Essential Oils'), ('skin', 'Skin Care Products'), ('tea', 'Tea and Infusion')], default='herbal', max_length=20),
        ),
    ]
